### ISSUE TITLE
Only 1 map loads per page

### ISSUE THREAD

**Issue by binx** [mapzen/mapzen.js#182]
On a page with multiple maps, only one of them is loading Tangram.
![image](https://cloud.githubusercontent.com/assets/589151/16635534/b3f76d02-4387-11e6-8939-ef79d6e61708.png)

There's an error in the console:
`[.CommandBufferContext.Offscreen-MainThread-0x7f90b538cff0]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 2`

**Comment by meetar** [comment]
At the moment Tangram's architecture only allows one map per browsing context – This is why we're using iframes for our demo posts… :/

**Comment by hanbyul-here** [comment]
If this issue is something Tangram team is not planning to fix in near future, as @migurski said

mapzen.js API should be rewritten to communicate that maps are a singleton.
i.e. “where would you like your one map” vs. more common Leaflet-style “put a map here, too”
Another possible approach might involve having subsequent maps throw an error, so the API still looks Leaflet-like but an informative error with a link to an issue is generated, rather than simple failure.

**Comment by migurski** [comment]
Given that a way to address this just a future possibility, I’d like to suggest that we throw an informative error with a link to something useful as a way of dealing with this.

**Comment by hanbyul-here** [comment]
What will be useful link about this issue, is tis somewhere documented? @bcamper @meetar

**Comment by migurski** [comment]
Let’s link to this new issue that @bcamper created: https://github.com/mapzen/mapzen.js/issues/182

**Comment by migurski** [comment]
Closed in https://github.com/mapzen/mapzen.js/pull/184.
