### ISSUE TITLE
BYOL (Bring Your Own Leaflet) version

### ISSUE THREAD

**Issue by stuporglue** [mapzen/mapzen.js#212]
It would be *REALLY* *REALLY* nice to have a version that doesn't bundle Leaflet. 

With Carto.js and Mapbox.js and now MapZen.js all including Leaflet.js it makes it very difficult to mix and match services. 

I realize that there are probably technical or logistical reasons to bundle Leaflet.js, but it'd be great to have a version that doesn't include it so I can bring my own copy of Leaflet.js, and make a MapZen map with a Carto animation, or an existing Mapbox basemap or something. 

Update: Mapbox does actually does provide a mapbox.standalone.js, it'd be great to have a standalone mapzen.js too.

**Comment by migurski** [comment]
Thanks @stuporglue! Can you provide a code sample or two of how this might work? We decided to bundle Leaflet because Tangram is sensitive to the version used.

While both Leaflet and Mapzen.js are waiting for a blessed 1.0 release, we may keep it as-is due to the sensitivity to breaking changes in pre-1.0 libraries.

**Comment by hanbyul-here** [comment]
Hey @stuporglue thanks for the issue. I worked on building standalone version of `mpazen.js` on this branch : https://github.com/mapzen/mapzen.js/tree/hanb/standalone 

You can build a standalone version of `mapzen.js` using `npm run build-standalone` command. 
I also added an example using mapbox geocoder with `mapzen.js` , which is `examples/standalone.html`.

This standalone one should make `mapzen.js` to work with other plugins based on Leaflet in theory. However, since we put our priority on easy use of all mapzen products through `mapzen.js`, some parts might not work as expected. (ex. `mapzen.js` puts Tangram tile layer on top of the map by default. `mapzen.js` doesn't have the api to change its default tile yet.)

**Comment by stuporglue** [comment]
Thanks! 

@migurski, I understand the version sensitivity issues, especially so close to a stable release. 

@hanbyul-here Thanks for the quick work of splitting it out to a standalone version!

I'm excited to play with this!
