### ISSUE TITLE
Continuous Zooming and Leaflet v1.0

### ISSUE THREAD

**Issue by dmvaldman** [mapzen/mapzen.js#249]
By upgrading to [Leaflet v1.0](https://github.com/Leaflet/Leaflet/releases) we can have continuous zooming of the map! The 1.0 releases are still in "candidate" mode, but Tangram (JS) has been using them for a while. It was pointed out to me that some other plugins may not be 1.0 compatible yet though. As an aside, it would be good to know what these plugins are that Mapzen.js would need.

**Comment by migurski** [comment]
Yeah! I think we want to be sure that we have our LRM story straight for this, but it might involve pushing change upstream like good OSS citizens.

**Comment by hanbyul-here** [comment]
LRM has working branches for [v1.0](https://github.com/perliedman/leaflet-routing-machine/tree/develop). Given some plugins waiting for Leaflet's v1.0 official release, I thought it would be better not to go ahead of Leaflet's release. (but I am not sure how many plugins are going to be affected by v1.0 release, so we can talk about this.)  There is a [standalone version of MapzenJS](https://github.com/mapzen/mapzen.js/tree/hanb/standalone) for the needs of using MapzenJS with other version of Leaflet!

**Comment by migurski** [comment]
We released a standalone version of this library today, which allows Leaflet 1.0 to be paired with Tangram. One thing we've noticed is that the scrollwheel zoom behavior is much too fast, and would love some input on that. It’ll be easier to show this behavior when #262 is done.

**Comment by hanbyul-here** [comment]
Also I never could see nice zoom that I can see I see on http://tangrams.github.io/tangram/ Is there anything more to do other than pairing tangram to Leaflet v1.0 ?

**Comment by meetar** [comment]
Yes – Tangram's scrolling behavior is a modification of leaflet's scrolling behavior, which has changed from version to version – so specific versions of Tangram expect to be paired to specific versions of leaflet so the scrolling works as expected. Eg: The latest release of Tangram expects the latest release of Leaflet, Tangram 0.8-0.9 is matched to leaflet 1.0.0-rc.3, and Tangram 0.7 and previous expects leaflet 1.0.0-beta.2 (…to the best of my knowledge, cc @bcamper). This isn't currently documented but should be. (Issue now here: https://github.com/tangrams/tangram-docs/issues/146)

**Comment by migurski** [comment]
Wow that’s interesting. Is there any way to configure the scroll behavior for the BYO-Leaflet version of Mapzen.js, or should we check for compatibility?

**Comment by meetar** [comment]
To my knowledge there's no way to adjust our modification at runtime, though hypothetically there could be – additionally there may be other per-leaflet adjustments and optimizations made elsewhere in the library, so I'd consider a switch similar to the initLeaflet() function in https://github.com/tangrams/tangram-frame/blob/gh-pages/main.js

**Comment by hanbyul-here** [comment]
Since we are injecting Tangram script later anyway, we can do the reversed version of Peter's example too. (detecting Leaflet, get version of it, and change the version of Tangram ) But we need working pairs of Tangram & Leaflet from Graphics team def.

**Comment by meetar** [comment]
So the crucial part for mapzen.js is the version of Leaflet? I'd assume for
mapzen users, the version of Tangram would be more important… but maybe I'm
misunderstanding the use case.

Either way we can definitely get you a list of official version pairings.

**Comment by bcamper** [comment]
IMO the only versions of Leaflet we should be supporting are:
- The now the official 1.x release
- 0.7.7, the last "legacy" release (we can reevaluate 0.7 support in the future based on 1.0 adoption, but as of now we know it has a wide install base)

It's not practical to support all the various 1.0 pre-releases and release candidates (there were about 5 of them?). They aren't officially supported by the Leaflet project itself, there were significant changes between them, and people using them are likely to be early adopters who can be reasonably expected to upgrade to the real 1.0 quickly. 

Tangram v0.10.5 has proper scroll wheel behavior with these two Leaflet versions (so anything pointing to 0.10.x will be fine). We should upgrade Mapzen.js to 0.10.

A related issue: we should add a way for Mapzen.js users to passthrough additional options for the Tangram Leaflet layer (see https://mapzen.com/documentation/tangram/Tangram-Overview/#options-object). Currently this will only be needed for advanced features, but one of those is the `modifyScrollWheel: false` option which can be used in cases where someone wants to disable Tangam's scroll wheel behavior (because they do want to try a different weird version of Leaflet, or it somehow interferes with the rest of their application in an unexpected way). This could be a `tangramOptions` object provided to Mapzen.js, for instance.

**Comment by meetar** [comment]
> A related issue: we should add a way for Mapzen.js users to passthrough additional options for the Tangram Leaflet layer

Issue tracked here: https://github.com/mapzen/mapzen.js/issues/260

**Comment by dmvaldman** [comment]
Woohoo!
