### ISSUE TITLE
Add user-friendly rate limit feedback

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#331]
use :sparkles: something :sparkles: in Mapzen.js to understand our rate limits and keys, and basically warn people for situations like:

- `you’re using mapzen-xxxxxx, it’s not real`
- `you have no key`
- `your key is over X limits` (second, minute, day)

/cc @migurski @sleepylemur

**Comment by migurski** [comment]
Note for @rfriberg / @hanbyul-here: the context here is that we'd like a strategy for allowing tiles and maps to work in demos and docs that makes it possible for casual users to try out our stuff without being susceptible to the periodic floods of game users we often see. Also, we’d like to make sure that the experience breaks rather than bends, so that someone tempted to copy/paste our demos for their own project will quickly learn that they should sign up for a free key.

We discussed a few possible places in our systems where engineering effort could be spent on this, and the idea of making this a Mapzen.js thing feels like an approach that can be developed quickly and cheaply. It also fits with Mapzen.js role as the entry point for our various services.

**Comment by migurski** [comment]
This may also interact with the idea of a rate limit endpoint. There was a discussion about this, but I can only find this stub issue copied over from the now-deleted ops-eng repo: https://github.com/mapzen/developer/issues/876

**Comment by rfriberg** [comment]
Thanks for the context, @migurski.  As a quick solution (prior to having a rate limit endpoint available), we can print to the console something along the lines of:

`You are using a rate-limited Mapzen demo key. To generate your own key, go to https://mapzen.com/developers` 

We are only requiring a key for use of the geocoder at this point (though have an option to pass a global key as well).  Was there any discussion on whether all of our services (those accessed through mapzen.js anyway) should be requiring a key?

**Comment by hanbyul-here** [comment]
Currently, if a user tries to use Search Component without a key, it works with very low qps limit so throws a 'Too many requests' error quickly. (and we show it through search component's UI, screenshot attached) If we have rate_limit api available, we probably can offer more meaningful messages. (ex. Whether a user needs a key, or exceeds the limit with a key) 

<img width="368" alt="screen shot 2017-01-05 at 3 20 48 pm" src="https://cloud.githubusercontent.com/assets/4583806/21696413/f1d887e6-d35b-11e6-868e-994157a372e7.png">

Aligning with @rfriberg  question, I also would like to know we want users to use api-key for tiles.

**Comment by migurski** [comment]
Nathaniel filled us in on some of the ways that our basemap styles currently obtain API keys through Tangram. We want to require Mapzen API keys in Mapzen.js, and to connect those to the "globals" feature of Refill, Zinc, etc.

**Comment by rfriberg** [comment]
To summarize:

1. Yes - we are going to require an API key for any use of mapzen.js - see issue #332 
2. Yes - we are going to use that API key for vector tiles via a `globals` parameter in Mapzen basemaps ( @nvkelso is going to provide an example of how he has done this in the past)
3. Relatedly, we also discussed adding a `basemapOptions` object to allow for easy toggling of the `globals` built in to Mapzen basemaps (e.g., vector tiles api key, ux_language) - see issue #333
