### ISSUE TITLE
Pass API key for vector tiles via Tangram globals parameter

### ISSUE THREAD

**Issue by rfriberg** [mapzen/mapzen.js#334]
Pass the required API key (see #332) (which may be overwritten in `tangramOptions`) to the included Mapzen basemap style for use with vector tiles.  This may be done via `global` parameters in Tangram.js.

**Comment by nvkelso** [comment]
Related Cartography documentation work here: 

- https://github.com/tangrams/cartography-docs/issues/2#issuecomment-259525739

Example usage in Bubble Wrap:

- https://github.com/tangrams/bubble-wrap/blob/gh-pages/index.html#L224-L230

Because the Mapzen basemap styles are versioned, and this will be a breaking change with a new major version I will publish the new styles at my leisure (probably next week?), but we will need to land support for the API key in Mapzen.js (this issue) before I update the house style major versions config in Mapzen.js.

- https://github.com/mapzen/mapzen.js/blob/master/src/js/components/basemapStyles.js

**Comment by hanbyul-here** [comment]
also some related discussion ( Some concerns + ideas about how to integrate apiKey to tiles were raised while making `L.Mapzen.apiKey` : https://github.com/mapzen/mapzen.js/pull/321

I think it might be better to keep the way to pass the apikey, and make `L.Mapzen.apiKey`'s jobs to handle all apikey underneath? (rather than making new spot to pass api key?)

**Comment by rfriberg** [comment]
@nvkelso - is the `global` parameter you're using for the basemap styles called `sdk_mapzen_api_key` or `sdk_api_key`.  I'm seeing both in https://github.com/tangrams/cartography-docs/issues/2#issuecomment-259525739 discussion.

**Comment by nvkelso** [comment]
@rfriberg we went with `sdk_mapzen_api_key`. 

Some examples (using Github rather than posting to the S3 bucket):

- https://raw.githubusercontent.com/tangrams/bubble-wrap/gh-pages/bubble-wrap.yaml
- https://raw.githubusercontent.com/tangrams/refill-style/gh-pages/refill-style.yaml
- https://raw.githubusercontent.com/tangrams/walkabout-style/gh-pages/walkabout-style.yaml

**Comment by hanbyul-here** [comment]
closing with 7a2984937a404a5072728349ef6894f66bedcf90
