### ISSUE TITLE
Bundle Tangram

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#419]
[Tangram is now bundlable!](https://www.npmjs.com/package/tangram) 
So we can bundle Tangram , and expose Tangram under `L.Mapzen` namespace.

**Comment by hanbyul-here** [comment]
This will require deprecating current api `tangramOptions: debug`. So this should happen with v1.0

**Comment by rfriberg** [comment]
@hanbyul-here and I discussed the argument that SemVer rules allow for this type of deprecating without make a major version change if the public API (a.k.a. v1.0) has not yet been released.  See [spec items 4-8](http://semver.org/#spec-item-4).

With that in mind, and because this deprecation would only affect users who are currently debugging Tangram (i.e., no one should be using the `debug` option in production), I propose that we move ahead with bundling tangram as part of the next minor version release (v0.9), rather than postponing to v1.0.  I don't want this to become a blocker for additional work nor do I want to rush a v1 when one of our major dependencies (Tangram) is still in beta.  

To cover anyone who still requires access the unminified version of Tangram (which is all the `debug` option really did), let's be sure to update documentation with instructions for doing so when this feature rolls out.
