### ISSUE TITLE
Unincorporated Areas?

### ISSUE THREAD

**Issue by shoxter** [mapzen/mapzen.js#433]
I'm trying to use Mapzen to create an address autocomplete, however, it's very inconvenient for our end users to not have cities associated with the address results they see.

I understand that unincorporated areas exist. The problem is, incorporating a service like Mapzen into our software isn't really viable because end users either don't care or don't understand why the addresses they're seeing lack cities. It's the only place they see that address without a city.

My question is, OpenAddresses has a great number of the unincorporated addresses in their search, but WITH the cities attached. 

Is Mapzen ex post facto removing the city to be "more correct?" Or is OpenAddresses adding in the city after the fact?

Is there something we can do about this? How does Google and other geocoding service providers accomplish this?

**Comment by dianashk** [comment]
Hey @shoxter! 👋 Thanks for reaching out.

Missing localities (cities) is a problem we've seen in certain parts of the US. We've discussed a variety of solutions, but haven't started down the implementation path for either of them just yet.
We do remove all admin data from our sources, such as *OpenAddresses* and *OpenStreetMap*, in order to normalize all the data against our own gazetteer, the *Who's on First* dataset.

In general, this is due to a concept we refer to as *Postal Cities*. You can read more about the underlying details [here](https://github.com/pelias/pelias/issues/396). If you have additional thoughts on this problem, feel free to weigh in on that issue directly. Thanks!
